Add SignUp and Home activity
wolox-training/co-android pull request #3
Opened 2021-09-10 14:39 UTC by camilo05

![Sep-10-2021 00-37-38](https://user-images.githubusercontent.com/23742708/132870638-a465eb8e-3545-434a-ba7e-b91809d8cacc.gif)

2021-09-10 15:34 UTC, rodrigo103 commented on app/src/main/java/ar/com/wolox/android/example/ui/home/HomeView.kt
> +interface HomeView
Usually we declare the view interface inside the fragment file. something like this:
```
class HomeFragment : WolmoFragment<FragmentHomeBinding, HomePresenter>(), HomeView {
    ...
}

interface HomeView {
    ....
}
```

2021-09-10 15:35 UTC, rodrigo103 commented on app/src/main/res/layout/fragment_signup.xml
> +
Delete this empty line

2021-09-10 15:37 UTC, rodrigo103 commented on app/src/main/res/layout/fragment_home.xml
> +
Delete this empty line, one is enough.

2021-09-10 15:44 UTC, rodrigo103 commented
Looks great!! I left some small comments

2021-09-10 15:45 UTC, rodrigo103 reviewed
Looks great!! I left some small comments

2021-09-10 17:13 UTC, LisandroDiMeo commented on app/src/main/java/ar/com/wolox/android/example/ui/home/HomeActivity.kt
> +        fun start(context: Context) = context.jumpTo(HomeActivity::class.java)
Keep in mind what `jumpTo` does, read its implementation 👍

2021-09-10 17:14 UTC, LisandroDiMeo approved these changes
Looks good! Just one comment to keep in mind theimplementation of a method

2021-09-10 18:29 UTC, ffasitella requested changes
I have just one comment: What happens when the user logs in, kills the app and then opens it again? The app should contain the logic to detect if the user is logged (reading UserSession) and redirect to the Home or the Login.

2021-09-13 15:15 UTC, ffasitella approved these changes
Amazing! 🚀

2021-09-13 15:17 UTC, rodrigo103 approved these changes
Well done!!

2021-09-13 15:18 UTC, merged