RecyclerView list news
wolox-training/co-android pull request #8
Opened 2021-09-23 19:13 UTC by camilo05

![Sep-23-2021 14-03-03](https://user-images.githubusercontent.com/23742708/134569187-dc589155-f1b1-4d79-a850-5775a5167d6b.gif)

2021-09-23 19:22 UTC, ffasitella requested changes
Well done! Left some feedback

2021-09-23 19:22 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/home/news/NewsFragment.kt
> +                Handler().postDelayed({
Nice! Remember to delete this when implementating the integration

2021-09-23 19:22 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/utils/ViewExtensions.kt
> +    return PrettyTime().format(Date(SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").parse(this).time))
Move this string to a constant

2021-09-23 19:22 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/utils/ViewExtensions.kt
> +fun ImageView.glideImage(url: String) = Glide.with(this).load(url).placeholder(ColorDrawable(Color.WHITE)).into(this)
Excellent!
Glide also provides the .error() method, so you can set an image to be rendered when the url has an error.

2021-09-23 19:22 UTC, ffasitella commented on app/src/main/res/layout/news_item.xml
> +            android:textSize="18sp"
Hardcoded dimen

2021-09-24 11:30 UTC, LisandroDiMeo commented on app/src/main/java/ar/com/wolox/android/example/ui/home/news/adapter/NewsAdapter.kt
> +    override fun getItemCount(): Int = presenter.getNewsRows()
Im not sure if its okay to have the presenter here. Usually the adapter only receives a *Collection* of elements, which will use to populate the recycler, and other parameters such like *Listeners*. In your case, passing the list of news to news adapter, will result in having the implementation of getItemCount with something like newsList.size.

2021-09-24 11:32 UTC, LisandroDiMeo requested changes
Just one comment! 💪

2021-09-24 18:09 UTC, rodrigo103 approved these changes
Great!!!

2021-09-24 18:29 UTC, LisandroDiMeo approved these changes
Great 👏

2021-09-27 14:35 UTC, ffasitella approved these changes
🙌🏽 ✨

2021-09-27 15:50 UTC, merged